[package]
name = "cyrly"
version = "0.1.0"
edition = "2021"

[dependencies]
ryu = "1.0.13"
serde = "1.0.159"
urlencoding = "2.1.2"

[dev-dependencies]
serde = { version = "1.0.159", features = ["derive"] }
serde_yaml = "0.9.19"

[lib]
path = "lib.rs"

[workspace]
members = ["bin"]
